

export const SET_TOKEN = "SET_TOKEN"
export const SET_USER_DETAIL = "SET_USER_DETAIL"
export const VERIFY_SELLER = "VERIFY_SELLER"
export const REMOVE_USER_DETAIL = "REMOVE_USER_DETAIL"
export const SET_LOCATION = "SET_LOCATION"
export const LOGOUT = "LOGOUT"
export const SET_MODE = "SET_MODE"
export const SET_ADDRESS = "SET_ADDRESS"
export const RECENT_POSTS = 'RECENT_POSTS'
export const SET_DELIVERY_TIME = 'SET_DELIVERY_TIME'
export const SET_AMOUNT = 'SET_AMOUNT'
export const SET_SELLER_MODE_PICKUP = 'SET_SELLER_MODE_PICKUP'
export const SET_SELLER_MODE_DELIVERY = 'SET_SELLER_MODE_DELIVERY'
export const SET_LIKE = 'SET_LIKE'
export const SET_KEYWORD = 'SET_KEYWORD'
export const EDIT_ITEM = 'EDIT_ITEM'